version: "3.5"
services:
  # nats:
  #   image: nats
  #   ports:
  #     - "8222:8222"
  #   command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
  #   networks: ["nats"]
  # nats-1:
  #   image: nats
  #   command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
  #   networks: ["nats"]
  #   depends_on: ["nats"]
  # nats-2:
  #   image: nats
  #   command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
  #   networks: ["nats"]
  #   depends_on: ["nats"]
  
  task_tracker:
    container_name: task_tracker.api
    image: shrigorevich/task-tracker:latest
    ports:
      - "1234:80"

  db:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    env_file:
      - docker.env
    networks:
      - postgres
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

networks:
  nats:
    name: nats
  postgres:
    driver: bridge